//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoenixLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoenixLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap dots {
            get {
                object obj = ResourceManager.GetObject("dots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find selected encryption in.
        /// </summary>
        internal static string Launcher_CannotFindEncryption {
            get {
                return ResourceManager.GetString("Launcher_CannotFindEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking client.
        /// </summary>
        internal static string Launcher_CheckingClient {
            get {
                return ResourceManager.GetString("Launcher_CheckingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Launcher_Done {
            get {
                return ResourceManager.GetString("Launcher_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Launcher_Error {
            get {
                return ResourceManager.GetString("Launcher_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while calculating client MD5 sum..
        /// </summary>
        internal static string Launcher_ErrorCalculatingMD5 {
            get {
                return ResourceManager.GetString("Launcher_ErrorCalculatingMD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error number.
        /// </summary>
        internal static string Launcher_ErrorNumber {
            get {
                return ResourceManager.GetString("Launcher_ErrorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Launcher_Exit {
            get {
                return ResourceManager.GetString("Launcher_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Launcher_Finished {
            get {
                return ResourceManager.GetString("Launcher_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known.
        /// </summary>
        internal static string Launcher_Known {
            get {
                return ResourceManager.GetString("Launcher_Known", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading server encryption keys.
        /// </summary>
        internal static string Launcher_LoadingEncryption {
            get {
                return ResourceManager.GetString("Launcher_LoadingEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patching client.
        /// </summary>
        internal static string Launcher_PatchingClient {
            get {
                return ResourceManager.GetString("Launcher_PatchingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running client.
        /// </summary>
        internal static string Launcher_RunningClient {
            get {
                return ResourceManager.GetString("Launcher_RunningClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string Launcher_Saving {
            get {
                return ResourceManager.GetString("Launcher_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string Launcher_Skipped {
            get {
                return ResourceManager.GetString("Launcher_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting client.
        /// </summary>
        internal static string Launcher_StartingClient {
            get {
                return ResourceManager.GetString("Launcher_StartingClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect Phoenix..
        /// </summary>
        internal static string Launcher_UnableToDetectPhoenix {
            get {
                return ResourceManager.GetString("Launcher_UnableToDetectPhoenix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resume client..
        /// </summary>
        internal static string Launcher_UnableToResumeClient {
            get {
                return ResourceManager.GetString("Launcher_UnableToResumeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start client..
        /// </summary>
        internal static string Launcher_UnableToStartClient {
            get {
                return ResourceManager.GetString("Launcher_UnableToStartClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Launcher_Unknown {
            get {
                return ResourceManager.GetString("Launcher_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating registry.
        /// </summary>
        internal static string Launcher_UpdatingRegistry {
            get {
                return ResourceManager.GetString("Launcher_UpdatingRegistry", resourceCulture);
            }
        }
    }
}
