using System;

namespace Phoenix.WorldData
{
    public enum StandardSpell : byte
    {
        Clumsy = 1,
        CreateFood = 2,
        Feeblemind = 3,
        Heal = 4,
        MagicArrow = 5,
        NightSight = 6,
        ReactiveArmor = 7,
        Weaken = 8,
        Agility = 9,
        Cunning = 10,
        Cure = 11,
        Harm = 12,
        MagicTrap = 13,
        MagicUntrap = 14,
        Protection = 15,
        Strength = 16,
        Bless = 17,
        Fireball = 18,
        MagicLock = 19,
        Poison = 20,
        Telekenisis = 21,
        Teleport = 22,
        Unlock = 23,
        WallofStone = 24,
        ArchCure = 25,
        ArchProtection = 26,
        Curse = 27,
        FireField = 28,
        GreaterHeal = 29,
        Lightning = 30,
        ManaDrain = 31,
        Recall = 32,
        BladeSpirit = 33,
        DispelField = 34,
        Incognito = 35,
        Reflection = 36,
        MindBlast = 37,
        Paralyze = 38,
        PoisonField = 39,
        SummonCreature = 40,
        Dispel = 41,
        EnergyBolt = 42,
        Explosion = 43,
        Invisibility = 44,
        Mark = 45,
        MassCurse = 46,
        ParalyzeField = 47,
        Reveal = 48,
        ChainLightning = 49,
        EnergyField = 50,
        FlameStrike = 51,
        GateTravel = 52,
        ManaVampire = 53,
        MassDispel = 54,
        MeteorShower = 55,
        Polymorph = 56,
        Earthquake = 57,
        EnergyVortex = 58,
        Ressurection = 59,
        SummonAirElemental = 60,
        SummonDaemon = 61,
        SummonEarthElemental = 62,
        SummonFireElemental = 63,
        SummonWaterElemental = 64
    }
}
